PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

CREATE TABLE IF NOT EXISTS MigrationSchema (
  version INTEGER PRIMARY KEY,
  dateApplication TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Utilisateur (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  identifiant INTEGER NOT NULL UNIQUE,
  motDePasse TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE COLLATE NOCASE,
  telephone TEXT,
  typeCompte TEXT NOT NULL CHECK (typeCompte IN ('ADMIN', 'PARENT', 'DRIVER', 'ASSISTANT')),
  prenom TEXT NOT NULL,
  nom TEXT NOT NULL,
  urlAvatar TEXT,
  actif INTEGER NOT NULL DEFAULT 1 CHECK (actif IN (0, 1)),
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifieLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Parent (
  id INTEGER PRIMARY KEY REFERENCES Utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Administrateur (
  id INTEGER PRIMARY KEY REFERENCES Utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Chauffeur (
  id INTEGER PRIMARY KEY REFERENCES Utilisateur(id) ON DELETE CASCADE,
  numeroPermis TEXT,
  dateExpirationPermis TEXT
);

CREATE TABLE IF NOT EXISTS Assistante (
  id INTEGER PRIMARY KEY REFERENCES Utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bus (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  matricule TEXT NOT NULL UNIQUE COLLATE NOCASE,
  libelle TEXT NOT NULL,
  capacite INTEGER NOT NULL CHECK (capacite > 0),
  statut TEXT NOT NULL DEFAULT 'AVAILABLE'
    CHECK (statut IN ('AVAILABLE', 'IN_SERVICE', 'MAINTENANCE', 'INACTIVE')),
  identifiantGPS TEXT UNIQUE,
  derniereMaintenanceLe TEXT,
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifieLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Etablissement (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nom TEXT NOT NULL UNIQUE COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS Trajet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE COLLATE NOCASE,
  nomTrajet TEXT NOT NULL,
  origine TEXT NOT NULL,
  destination TEXT NOT NULL,
  heureMatin TEXT NOT NULL,
  heureApresMidi TEXT NOT NULL,
  tempsTotalEstime REAL,
  actif INTEGER NOT NULL DEFAULT 1 CHECK (actif IN (0, 1)),
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifieLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Arret (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idTrajet INTEGER NOT NULL REFERENCES Trajet(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  adresse TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  ordreArret INTEGER NOT NULL CHECK (ordreArret >= 0),
  estimationTemps REAL NOT NULL DEFAULT 0 CHECK (estimationTemps >= 0),
  UNIQUE (idTrajet, ordreArret)
);

CREATE TABLE IF NOT EXISTS Enfant (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idParent INTEGER NOT NULL REFERENCES Parent(id) ON DELETE RESTRICT,
  prenom TEXT NOT NULL,
  nom TEXT NOT NULL,
  dateNaissance TEXT,
  classe TEXT,
  adresseDomicile TEXT NOT NULL,
  latitudeDomicile REAL NOT NULL,
  longitudeDomicile REAL NOT NULL,
  rayonAlerteM INTEGER NOT NULL DEFAULT 500 CHECK (rayonAlerteM BETWEEN 50 AND 5000),
  idEtablissement INTEGER REFERENCES Etablissement(id) ON DELETE SET NULL,
  actif INTEGER NOT NULL DEFAULT 1 CHECK (actif IN (0, 1)),
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifieLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TrajetEnfant (
  idTrajet INTEGER NOT NULL REFERENCES Trajet(id) ON DELETE CASCADE,
  idEnfant INTEGER NOT NULL REFERENCES Enfant(id) ON DELETE CASCADE,
  idArret INTEGER NOT NULL REFERENCES Arret(id) ON DELETE RESTRICT,
  actif INTEGER NOT NULL DEFAULT 1 CHECK (actif IN (0, 1)),
  affecteLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (idTrajet, idEnfant)
);

CREATE TABLE IF NOT EXISTS Affectation (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idTrajet INTEGER NOT NULL REFERENCES Trajet(id) ON DELETE RESTRICT,
  idBus INTEGER NOT NULL REFERENCES Bus(id) ON DELETE RESTRICT,
  idChauffeur INTEGER NOT NULL REFERENCES Chauffeur(id) ON DELETE RESTRICT,
  idAssistante INTEGER REFERENCES Assistante(id) ON DELETE RESTRICT,
  debutLe TEXT NOT NULL,
  finLe TEXT,
  actif INTEGER NOT NULL DEFAULT 1 CHECK (actif IN (0, 1)),
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_affectation_trajet_actif
  ON Affectation(idTrajet) WHERE actif = 1;

CREATE TABLE IF NOT EXISTS ExecutionTrajet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idTrajet INTEGER NOT NULL REFERENCES Trajet(id) ON DELETE RESTRICT,
  idBus INTEGER NOT NULL REFERENCES Bus(id) ON DELETE RESTRICT,
  idChauffeur INTEGER NOT NULL REFERENCES Chauffeur(id) ON DELETE RESTRICT,
  idAssistante INTEGER REFERENCES Assistante(id) ON DELETE RESTRICT,
  sens TEXT NOT NULL CHECK (sens IN ('MORNING', 'AFTERNOON')),
  statut TEXT NOT NULL DEFAULT 'PLANNED'
    CHECK (statut IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  departPrevuLe TEXT NOT NULL,
  departReelLe TEXT,
  finReelleLe TEXT,
  retardMinutes INTEGER NOT NULL DEFAULT 0,
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifieLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_execution_trajet_horaire ON ExecutionTrajet(departPrevuLe);
CREATE INDEX IF NOT EXISTS idx_execution_trajet_equipe ON ExecutionTrajet(idChauffeur, idAssistante);

CREATE TABLE IF NOT EXISTS ArretExecution (
  idExecutionTrajet INTEGER NOT NULL REFERENCES ExecutionTrajet(id) ON DELETE CASCADE,
  idArret INTEGER NOT NULL REFERENCES Arret(id) ON DELETE RESTRICT,
  prevuLe TEXT,
  arriveLe TEXT,
  statut TEXT NOT NULL DEFAULT 'UPCOMING'
    CHECK (statut IN ('UPCOMING', 'APPROACHING', 'PASSED', 'SKIPPED')),
  PRIMARY KEY (idExecutionTrajet, idArret)
);

CREATE TABLE IF NOT EXISTS PresenceEnfant (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idExecutionTrajet INTEGER NOT NULL REFERENCES ExecutionTrajet(id) ON DELETE CASCADE,
  idEnfant INTEGER NOT NULL REFERENCES Enfant(id) ON DELETE RESTRICT,
  statut TEXT NOT NULL CHECK (statut IN ('WAITING', 'BOARDED', 'ABSENT', 'DROPPED_OFF')),
  heureMontee TEXT,
  heureDescente TEXT,
  enregistrePar INTEGER REFERENCES Utilisateur(id) ON DELETE SET NULL,
  enregistreLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PositionGPS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idBus INTEGER NOT NULL REFERENCES Bus(id) ON DELETE CASCADE,
  idExecutionTrajet INTEGER REFERENCES ExecutionTrajet(id) ON DELETE SET NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  vitesseKmh REAL NOT NULL DEFAULT 0,
  direction REAL NOT NULL DEFAULT 0,
  precisionM REAL,
  enregistreLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_position_gps_bus_date ON PositionGPS(idBus, enregistreLe DESC);

CREATE TABLE IF NOT EXISTS Notification (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idUtilisateur INTEGER NOT NULL REFERENCES Utilisateur(id) ON DELETE CASCADE,
  idExecutionTrajet INTEGER REFERENCES ExecutionTrajet(id) ON DELETE SET NULL,
  type TEXT NOT NULL DEFAULT 'INFO'
    CHECK (type IN ('INFO', 'APPROACH', 'DELAY', 'INCIDENT', 'TRIP_STARTED', 'TRIP_ENDED')),
  titre TEXT NOT NULL,
  message TEXT NOT NULL,
  luLe TEXT,
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notification_utilisateur ON Notification(idUtilisateur, creeLe DESC);

CREATE TABLE IF NOT EXISTS Incident (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  signalePar INTEGER NOT NULL REFERENCES Utilisateur(id) ON DELETE RESTRICT,
  idExecutionTrajet INTEGER REFERENCES ExecutionTrajet(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN ('DELAY', 'BEHAVIOUR', 'VEHICLE', 'ROUTE', 'SAFETY', 'OTHER')),
  description TEXT NOT NULL,
  retardMinutes INTEGER NOT NULL DEFAULT 0,
  statut TEXT NOT NULL DEFAULT 'OPEN'
    CHECK (statut IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED')),
  resolution TEXT,
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resoluLe TEXT
);

CREATE TABLE IF NOT EXISTS Reclamation (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sujet TEXT NOT NULL,
  description TEXT NOT NULL,
  statut TEXT NOT NULL DEFAULT 'OPEN',
  idParent INTEGER NOT NULL REFERENCES Parent(id) ON DELETE RESTRICT,
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DemandeInscription (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  typeCompteDemande TEXT NOT NULL CHECK (typeCompteDemande IN ('PARENT', 'DRIVER', 'ASSISTANT')),
  prenom TEXT NOT NULL,
  nom TEXT NOT NULL,
  email TEXT NOT NULL COLLATE NOCASE,
  telephone TEXT,
  statut TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (statut IN ('PENDING', 'APPROVED', 'REJECTED')),
  examinePar INTEGER REFERENCES Administrateur(id) ON DELETE SET NULL,
  creeLe TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  examineLe TEXT
);

INSERT OR IGNORE INTO MigrationSchema(version) VALUES (2);
